[project]
name = "smart-contracts-vyper-solana"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "titanoboa>=0.2.8",
    "vyper>=0.4.3",
    "web3>=7.14.0",
]
